### ISSUE TITLE
Blueprint Idea: 1 sec update and reboot

### ISSUE THREAD

**Issue by Mannshoch** [Vanilla-OS/vanilla-updates-utility#16]
After A discussion with a friend We Came with an Idea we think would be best proposed here on this innovative system. We are both no developer so maybe the idea is not that good as it sound in our head.

We assume that a Linux sytem use a hypervisorconcept (like proxmox)

1. First an update arrive as usual and get installed without userfeedback as into A
2. Instead requesting for a reboot, the system virtual start a second VM innto B
3. If needed, an auto login with a Dummy account happens and runs some tests if the update runs with the updated system.
    In this setting currently unused Hardware should be redirected to the other vm to check if drivers work. 
    Graphiccard could be a problem. May the moment of a screenlock could be used for that. The graphiccard get redirected to B the screensaver came for a short time, whil testing the driver from there. and switch back after that.
5. Currenty two system runs.  A with main Hardware acces and B Virtual.
6. The user is asked for reboot. The user recognice the first time that an update is there
7. A logout with session restore happen (Like KDE does) and the grahic output get redirected from one to the other VM 
8. Instand a login on the other VM with Session restore happen and B shutdown.
9. That way may a 1second update - as seen by the user - is happen.

This Idea came while discousse about usability of session restore. (I never use it I power off oder hibernate) and this case is the only case we come across where we could use a session restore.

**Comment by taukakao** [comment]
It's an interesting idea but running two systems side by side is very expensive, so this would come at a huge performance cost.

Also, I don't think two OSs can use the same drive at the same time. That could theoretically be handled by the hypervisor but then you would still have race conditions from two versions of the same executable accessing the same data. 

It could probably be done by duplicating the data with a CoW filesystem or something but it would be pretty difficult. 

The biggest problem to this concept is that you would still need to upgrade the hypervisor, which would in this case do a lot of the work. So the problem of upgrading the system just got shifted somewhere else.

I still think there is something to this concept, but it would probably require specialized hardware and a lot of underlying software to make it work.

**Comment by Mannshoch** [comment]
> It's an interesting idea but running two systems side by side is very expensive, so this would come at a huge performance cost.

I'm not sure,  In this case B is not a user or server system. So it do not have to run fast. It only has to run reliable. The startup of A could need 10s and B could reduced until a boot need 5min in the lowest priority.
No, I think performance is not a valid argument. May RAM usage could be one, but if you have a writable file so you could use a SWAP file here.

> Also, I don't think two OSs can use the same drive at the same time. That could theoretically be handled by the 
hypervisor but then you would still have race conditions from two versions of the same executable accessing the same data.
> It could probably be done by duplicating the data with a CoW filesystem or something but it would be pretty difficult.

Vanila as imutable with A/B system. And B in this case where nothing has to be written to disk (even the log result of the B test may simply transfered over a network api to the running A.
No I don't think that is a problem 
 
> The biggest problem to this concept is that you would still need to upgrade the hypervisor, which would in this case do a lot of the work. So the problem of upgrading the system just got shifted somewhere else.

Yes right, the Hypervisor need also Updates. I assume the Hypervisor itself may do not need that much update then the rest of the system. And may also the Hypervisor could be fast updated. 

1. HypervisorA is Running
2. Update arrive 
3. Installed into HypervisorB
4. Mainsystem get suspended
5. Hypervisor reboot
6. Main system get resumed

1-3 Could be done while running 4-6 while the main system is in screensaver mode. 
In this case an Update could even be saver in terms of data loss because hibernating a system cause less trouble than logout and session restore. I only assume that the update of a hypervisor take longer than the system update described above because suspending and restoring need time.

> I still think there is something to this concept, but it would probably require specialized hardware and a lot of underlying software to make it work.

Thanks a lot. 
One of the core of the Idea is also Proxmox. Because of the Broadcom happening, Proxmox is everywhere mentioned. And every modern hardware support virtualizing - I even found a [Raspberry PI solution as Proxmox Server](https://pimylifeup.com/raspberry-pi-proxmox/).
I think that it is correct that Hardware is a Key here but more in the way of it's creation date and not in terms of special or expensive.

**Comment by taukakao** [comment]
> And B in this case where nothing has to be written to disk

Sure, the root system in Vanilla is read only but you still have apps downloading and writing data, changing settings, accessing databases, etc.

**Comment by Mannshoch** [comment]
May into a temp like a life system?

**Comment by taukakao** [comment]
Ok, so while I still think that this is an interesting idea, it would be a completely different OS.
It might be built with some vanilla tools but it would not be very similar otherwise. 

Thus, it is not in scope for Vanilla OS
